Added alias for finding a file, for monitoring resources(with top) and performing a checksum in a folder

diff --git a/custom_aliases b/custom_aliases
--- a/custom_aliases
+++ b/custom_aliases
@@ -2,3 +2,18 @@
 alias hibernate='sudo echo "Hibernating..."; gnome-screensaver-command -l; sudo pm-hibernate;'
 alias restart_wifi='sudo echo "Restarting Wifi..."; sudo /etc/init.d/network-manager restart;'
 alias find_file='function _find_file(){ if [ "$#" -ne 1 ]; then echo "Usage find_file <filename>"; exit 1; else find . -type f -name "$1"; fi }; _find_file $1'
+alias monitor='top'
+alias check='function _checksum_folder(){ 
+if [ "$#" -ne 0 ]; then
+   	 if ! [ -d "$1" ];
+ 	  then echo "Usage $0 [dir]";
+ 	   echo "No arg required. Checksum over the current folder or over the passed folder.";
+  	   return 1;
+  	  else
+  	   find "$1" -xtype f -print0 | xargs -0 sha1sum | cut -b-40 | sort | sha1sum;
+  	 fi
+else
+      find . -xtype f -print0 | xargs -0 sha1sum | cut -b-40 | sort | sha1sum; 
+fi
+}; _checksum_folder $1'
+# the idea is you hash all the files cut out the hashes one per line, sort them and hash that yielding a single hash. this doesn't depend on the names of the files. From http://serverfault.com/questions/303365/calculate-md5-checksum-of-a-directory
